channels:
  - conda-forge
dependencies:
  - python=3.8.20
  - pip
  - pip:
    - mlflow==2.21.2
    - boto3==1.28.30
    - cffi==1.16.0
    - configparser==5.4.0
    - dill==0.3.7
    - fsspec==2025.5.1
    - keras==2.12.0
    - pandas==2.3.0
    - pillow==10.2.0
    - scipy==1.11.1
    - tensorflow==2.13.0
    - tensorflow-cpu==2.13.0
    - typing-extensions==4.7.1
name: mlflow-env
